apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-sprint-monit-sync
  labels:
    app: ai-sprint-monit-sync
spec:
  selector:
    matchLabels:
      app: ai-sprint-monit-sync
  template:
    metadata:
      name: ai-sprint-monit-sync
      labels:
        app: ai-sprint-monit-sync
    spec:
      restartPolicy: Always
      containers:
        - name: monit-sync
          image: registry.gitlab.polimi.it/ai-sprint/monitoring-subsystem/ai-sprint-monit-sync:latest
          envFrom:
            - configMapRef:
                name: ai-sprint-monit-sync
            - secretRef:
                name: ai-sprint-monit-sync
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
