apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-sprint-monit-api-nginx
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        location / {
            include uwsgi_params;
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host $host ;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto: http;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 10;
        }
    }
